"use client";

import React, { createContext, useContext, useState } from "react";

export type Language = "en" | "ka";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("ka");

  const t = (key: string): string => {
    const translations = language === "en" ? enTranslations : kaTranslations;
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const enTranslations: Record<string, string> = {
  "nav.findATVs": "Find ATVs",
  "nav.sellMyATV": "Sell my ATV",
  "nav.research": "Research",
  "nav.atvDealers": "ATV dealers",
  "nav.blog": "Blog",
  "nav.login": "Log in",
  "nav.search": "Search",
  "hero.title": "Find your perfect ATV",
  "hero.subtitle": "Browse thousands of ATVs for sale from dealers and private sellers",
  "hero.searchPlaceholder": "Enter keywords (e.g., Honda, Yamaha)",
  "hero.zipPlaceholder": "Enter ZIP code",
  "hero.radius": "Radius",
  "hero.onlineListings": "Include online listings",
  "hero.searchButton": "Search ATVs",
  "hero.sellLink": "Sell your ATV",
  "brands.title": "ATVs for every outdoor adventure",
  "brands.makes": "Makes",
  "brands.types": "Types",
  "brands.seeAll": "See all makes",
  "featured.title": "Featured listings",
  "featured.viewAll": "View All Featured",
  "featured.miles": "miles",
  "sell.title": "Sell your ATV",
  "sell.description": "List your ATV for free and reach thousands of potential buyers",
  "sell.button": "List Your ATV",
  "sell.today": "List your ATV today",
  "buyOnline.title": "Buy online",
  "buyOnline.description": "Purchase ATVs from verified dealers with secure transactions",
  "buyOnline.button": "Buy Now",
  "info.title": "Find ATVs for Sale on ATV Trader",
  "info.description": "ATV Trader is the leading marketplace for buying and selling all-terrain vehicles. Whether you're looking for a sport ATV, utility ATV, or side-by-side, we have thousands of listings from dealers and private sellers across the country.",
  "footer.makes": "Top Four Wheeler Makes",
  "footer.models": "Top Four Wheeler Make/Models",
  "footer.types": "Top Four Wheeler Types",
  "footer.sxs": "Side by Side",
  "footer.atv": "ATV Four Wheeler",
  "footer.trailer": "Trailer",
  "footer.golfCarts": "Golf Carts",
  "footer.copyright": "© 2025 ATV Trader. All rights reserved.",
  "findATVs.title": "Find ATVs",
  "findATVs.results": "ATVs for sale",
  "findATVs.noResults": "No ATVs found matching your criteria",
  "findATVs.sortBy": "Sort by",
  "findATVs.sortNewest": "Newest First",
  "findATVs.sortPrice": "Price: Low to High",
  "findATVs.sortPriceDesc": "Price: High to Low",
  "findATVs.sortYear": "Year: New to Old",
  "findATVs.sortYearOld": "Year: Old to New",
  "findATVs.sortMileage": "Mileage: Low to High",
  "findATVs.previous": "Previous",
  "findATVs.next": "Next",
  "findATVs.noATVsFound": "No ATVs Found",
  "findATVs.tryChanging": "Try changing your search criteria or clearing the filters.",
  "filters.price": "Price",
  "filters.minPrice": "Min Price",
  "filters.maxPrice": "Max Price",
  "filters.year": "Year",
  "filters.minYear": "Min Year",
  "filters.maxYear": "Max Year",
  "filters.mileage": "Mileage",
  "filters.maxMileage": "Max Mileage",
  "filters.condition": "Condition",
  "filters.new": "New",
  "filters.used": "Used",
  "filters.engineSize": "Engine Size",
  "filters.location": "Location",
  "filters.zipCode": "ZIP Code",
  "filters.applyFilters": "Apply Filters",
  "filters.clearFilters": "Clear Filters",
  "filters.manufacturer": "Manufacturer",
  "filters.selectManufacturer": "Select manufacturer",
  "filters.model": "Model",
  "filters.modelName": "Model name",
  "filters.priceGEL": "Price (GEL)",
  "filters.yearOfManufacture": "Year of Manufacture",
  "filters.mileageKm": "Mileage (km)",
  "filters.selectCondition": "Select condition",
  "filters.excellent": "Excellent",
  "filters.good": "Good",
  "filters.fair": "Fair",
  "filters.needsRepair": "Needs Repair",
  "filters.selectEngineSize": "Select engine size",
  "filters.selectCity": "Select city",
  "filters.category": "Category",
  "filters.selectCategory": "Select category",
  "filters.sport": "Sport",
  "filters.utility": "Utility",
  "filters.youth": "Youth",
  "filters.touring": "Touring",
  "filters.racing": "Racing",
  "filters.recreational": "Recreational",
  "listing.call": "Call",
  "listing.year": "year",
  "listing.mileage": "km",
  "signup.title": "Create Account",
  "signup.subtitle": "Join ATV Trader to buy and sell ATVs",
  "signup.firstName": "First Name",
  "signup.firstNamePlaceholder": "First name",
  "signup.lastName": "Last Name",
  "signup.lastNamePlaceholder": "Last name",
  "signup.email": "Email",
  "signup.emailPlaceholder": "Enter your email",
  "signup.phone": "Phone",
  "signup.phonePlaceholder": "Enter your phone",
  "signup.password": "Password",
  "signup.passwordPlaceholder": "Create a password",
  "signup.confirmPassword": "Confirm Password",
  "signup.confirmPasswordPlaceholder": "Confirm your password",
  "signup.agreeToTerms": "I agree to the",
  "signup.termsOfService": "Terms of Service",
  "signup.and": "and",
  "signup.privacyPolicy": "Privacy Policy",
  "signup.button": "Create Account",
  "signup.haveAccount": "Already have an account?",
  "signup.login": "Log in",
  "login.title": "Log in to your account",
  "login.email": "Email",
  "login.password": "Password",
  "login.button": "Sign in",
  "login.forgotPassword": "Forgot your password?",
  "login.noAccount": "Don't have an account?",
  "login.signUp": "Sign up",
  "contact.title": "Contact Us",
  "contact.subtitle": "Get in touch with our team for any questions or support",
  "contact.sendMessage": "Send us a message",
  "contact.formDesc": "Fill out the form below and we'll get back to you as soon as possible",
  "contact.name": "Name",
  "contact.namePlaceholder": "Your full name",
  "contact.email": "Email",
  "contact.emailPlaceholder": "Your email address",
  "contact.subject": "Subject",
  "contact.subjectPlaceholder": "What is this about?",
  "contact.message": "Message",
  "contact.messagePlaceholder": "Tell us more details...",
  "contact.sendButton": "Send Message",
  "contact.getInTouch": "Get in touch",
  "contact.channels": "Reach out to us through any of these channels",
  "contact.emailLabel": "Email",
  "contact.phoneLabel": "Phone",
  "contact.addressLabel": "Address",
  "contact.businessHours": "Business Hours",
  "contact.monFri": "Monday - Friday",
  "contact.monFriHours": "9:00 AM - 6:00 PM",
  "contact.saturday": "Saturday",
  "contact.saturdayHours": "10:00 AM - 4:00 PM",
  "contact.sunday": "Sunday",
  "contact.sundayHours": "Closed",
  "about.title": "About ATV Trader",
  "about.subtitle": "We're the leading marketplace for all-terrain vehicles, connecting buyers and sellers across the nation with the best selection of ATVs, UTVs, and side-by-sides.",
  "about.ourStory": "Our Story",
  "about.storyP1": "Founded in 2010 by a group of ATV enthusiasts, ATV Trader was born from the frustration of not having a dedicated platform to buy and sell all-terrain vehicles.",
  "about.storyP2": "What started as a small community forum has grown into the largest ATV marketplace in North America, facilitating thousands of transactions every month.",
  "about.storyP3": "Today, we're proud to serve both recreational riders and professional dealers, providing tools and resources that make buying and selling ATVs easier than ever.",
  "about.ourMission": "Our Mission",
  "about.missionP1": "To create the most trusted and comprehensive marketplace for ATV enthusiasts, where every transaction is safe, transparent, and beneficial for all parties involved.",
  "about.missionP2": "We believe that adventure should be accessible to everyone, and we're committed to helping people find their perfect ATV at the right price.",
  "about.whyChoose": "Why Choose ATV Trader?",
  "about.communityFirst": "Community First",
  "about.communityFirstDesc": "Built by ATV enthusiasts for ATV enthusiasts. We understand your passion.",
  "about.trustedMarketplace": "Trusted Marketplace",
  "about.trustedMarketplaceDesc": "Verified dealers and private sellers. Safe and secure transactions.",
  "about.qualityGuaranteed": "Quality Guaranteed",
  "about.qualityGuaranteedDesc": "Every listing is reviewed. Only quality ATVs make it to our platform.",
  "about.nationwideReach": "Nationwide Reach",
  "about.nationwideReachDesc": "Find ATVs anywhere in the country. Local and nationwide shipping options.",
  "about.byTheNumbers": "By the Numbers",
  "about.activeListings": "Active Listings",
  "about.registeredUsers": "Registered Users",
  "about.verifiedDealers": "Verified Dealers",
  "about.yearsExperience": "Years of Experience",
  "about.meetTeam": "Meet Our Team",
  "about.teamDesc": "We're a passionate team of ATV enthusiasts, developers, and customer service experts dedicated to providing the best experience for our users.",
  "about.ceo": "CEO & Founder",
  "about.ceoDesc": "30+ years of ATV experience",
  "about.headProduct": "Head of Product",
  "about.headProductDesc": "Tech leader with racing background",
  "about.customerSuccess": "Customer Success",
  "about.customerSuccessDesc": "Dedicated to user satisfaction",
  "dealers.title": "ATV Dealers",
  "dealers.findNearYou": "Find ATV Dealers Near You",
  "dealers.description": "Dealer directory, locations, contact information, and dealer profiles will be implemented here.",
  "blog.title": "Blog",
  "blog.heading": "ATV News, Tips & Guides",
  "blog.description": "Blog articles, ATV guides, news, maintenance tips, and community content will be implemented here.",
  "research.title": "Research",
  "research.heading": "ATV Research & Reviews",
  "research.description": "ATV specifications, reviews, comparisons, and research tools will be implemented here.",
  "notFound.title": "404",
  "notFound.message": "Oops! Page not found",
  "notFound.returnHome": "Return to Home",
  "recommended.title": "Recommended ATVs",
  "recommended.viewAll": "View All Recommendations",
  "recommended.save": "Save",
  "terms.title": "Terms of Service",
  "privacy.title": "Privacy Policy",
};

const kaTranslations: Record<string, string> = {
  "nav.findATVs": "კვადროების ძებნა",
  "nav.sellMyATV": "ჩემი კვადროს გაყიდვა",
  "nav.research": "კვლევა",
  "nav.atvDealers": "კვადროების დილერები",
  "nav.blog": "ბლოგი",
  "nav.login": "შესვლა",
  "nav.search": "ძებნა",
  "hero.title": "იპოვეთ თქვენი იდეალური კვადრო",
  "hero.subtitle": "დაათვალიერეთ ათასობით კვადრო გასაყიდად დილერებისა და კერძო გამყიდველებისგან",
  "hero.searchPlaceholder": "შეიყვანეთ საძიებო სიტყვები (მაგ., Honda, Yamaha)",
  "hero.zipPlaceholder": "შეიყვანეთ ZIP კოდი",
  "hero.radius": "რადიუსი",
  "hero.onlineListings": "ონლაინ განცხადებების ჩათვლით",
  "hero.searchButton": "კვადროების ძებნა",
  "hero.sellLink": "გაყიდეთ თქვენი კვადრო",
  "brands.title": "კვადროები ყველა გარე თავგადასავლისთვის",
  "brands.makes": "მარკები",
  "brands.types": "ტიპები",
  "brands.seeAll": "ყველა მარკის ნახვა",
  "featured.title": "გამორჩეული განცხადებები",
  "featured.viewAll": "ყველა გამორჩეულის ნახვა",
  "featured.miles": "მილი",
  "sell.title": "გაყიდეთ თქვენი კვადრო",
  "sell.description": "განათავსეთ თქვენი კვადრო უფასოდ და მიაღწიეთ ათასობით პოტენციურ მყიდველს",
  "sell.button": "განათავსეთ კვადრო",
  "sell.today": "განათავსეთ თქვენი კვადრო დღესვე",
  "buyOnline.title": "ონლაინ ყიდვა",
  "buyOnline.description": "შეიძინეთ კვადროები დადასტურებული დილერებისგან უსაფრთხო ტრანზაქციებით",
  "buyOnline.button": "ახლავე იყიდეთ",
  "info.title": "იპოვეთ კვადროები გასაყიდად ATV Trader-ზე",
  "info.description": "ATV Trader არის წამყვანი მარკეტპლეისი ყველა ტიპის ტრანსპორტის ყიდვა-გაყიდვისთვის.",
  "footer.makes": "ტოპ ოთხბორბლიანის მარკები",
  "footer.models": "ტოპ ოთხბორბლიანის მარკა/მოდელები",
  "footer.types": "ტოპ ოთხბორბლიანის ტიპები",
  "footer.sxs": "გვერდი გვერდთან",
  "footer.atv": "კვადროციკლი",
  "footer.trailer": "ტრეილერი",
  "footer.golfCarts": "გოლფ მანქანები",
  "footer.copyright": "© 2025 ATV Trader. ყველა უფლება დაცულია.",
  "findATVs.title": "კვადროების ძებნა",
  "findATVs.results": "კვადროები გასაყიდად",
  "findATVs.noResults": "თქვენს კრიტერიუმებს შესაბამისი კვადროები ვერ მოიძებნა",
  "findATVs.sortBy": "დალაგება",
  "findATVs.sortNewest": "ყველაზე ახალი",
  "findATVs.sortPrice": "ფასი: დაბალიდან მაღალამდე",
  "findATVs.sortPriceDesc": "ფასი: მაღალიდან დაბალამდე",
  "findATVs.sortYear": "წელი: ახლიდან ძველამდე",
  "findATVs.sortYearOld": "წელი: ძველიდან ახლამდე",
  "findATVs.sortMileage": "გარბენი: ნაკლებიდან მეტამდე",
  "findATVs.previous": "წინა",
  "findATVs.next": "შემდეგი",
  "findATVs.noATVsFound": "ვერ მოიძებნა კვადროციკლი",
  "findATVs.tryChanging": "სცადეთ ძიების კრიტერიუმების შეცვლა ან ფილტრების გასუფთავება.",
  "filters.price": "ფასი",
  "filters.minPrice": "მინ. ფასი",
  "filters.maxPrice": "მაქს. ფასი",
  "filters.year": "წელი",
  "filters.minYear": "მინ. წელი",
  "filters.maxYear": "მაქს. წელი",
  "filters.mileage": "გარბენი",
  "filters.maxMileage": "მაქს. გარბენი",
  "filters.condition": "მდგომარეობა",
  "filters.new": "ახალი",
  "filters.used": "გამოყენებული",
  "filters.engineSize": "ძრავის მოცულობა",
  "filters.location": "ლოკაცია",
  "filters.zipCode": "ZIP კოდი",
  "filters.applyFilters": "ფილტრების გამოყენება",
  "filters.clearFilters": "ფილტრების გასუფთავება",
  "filters.manufacturer": "მწარმოებელი",
  "filters.selectManufacturer": "აირჩიეთ მწარმოებელი",
  "filters.model": "მოდელი",
  "filters.modelName": "მოდელის სახელი",
  "filters.priceGEL": "ფასი (ლარი)",
  "filters.yearOfManufacture": "გამოშვების წელი",
  "filters.mileageKm": "გარბენი (კმ)",
  "filters.selectCondition": "აირჩიეთ მდგომარეობა",
  "filters.excellent": "ძალიან კარგი",
  "filters.good": "კარგი",
  "filters.fair": "საშუალო",
  "filters.needsRepair": "საჭიროებს შეკეთებას",
  "filters.selectEngineSize": "აირჩიეთ მოცულობა",
  "filters.selectCity": "აირჩიეთ ქალაქი",
  "filters.category": "კატეგორია",
  "filters.selectCategory": "აირჩიეთ კატეგორია",
  "filters.sport": "სპორტული",
  "filters.utility": "საკომუნალო",
  "filters.youth": "ახალგაზრდობისთვის",
  "filters.touring": "ტურისტული",
  "filters.racing": "რასინგი",
  "filters.recreational": "გასართობი",
  "listing.call": "დარეკვა",
  "listing.year": "წ.",
  "listing.mileage": "კმ",
  "signup.title": "ანგარიშის შექმნა",
  "signup.subtitle": "შეუერთდით ATV Trader-ს კვადროების ყიდვა-გაყიდვისთვის",
  "signup.firstName": "სახელი",
  "signup.firstNamePlaceholder": "სახელი",
  "signup.lastName": "გვარი",
  "signup.lastNamePlaceholder": "გვარი",
  "signup.email": "ელ-ფოსტა",
  "signup.emailPlaceholder": "შეიყვანეთ ელ-ფოსტა",
  "signup.phone": "ტელეფონი",
  "signup.phonePlaceholder": "შეიყვანეთ ტელეფონის ნომერი",
  "signup.password": "პაროლი",
  "signup.passwordPlaceholder": "შექმენით პაროლი",
  "signup.confirmPassword": "პაროლის დადასტურება",
  "signup.confirmPasswordPlaceholder": "დაადასტურეთ პაროლი",
  "signup.agreeToTerms": "ვეთანხმები",
  "signup.termsOfService": "მომსახურების პირობებს",
  "signup.and": "და",
  "signup.privacyPolicy": "კონფიდენციალურობის პოლიტიკას",
  "signup.button": "ანგარიშის შექმნა",
  "signup.haveAccount": "უკვე გაქვთ ანგარიში?",
  "signup.login": "შესვლა",
  "login.title": "შესვლა თქვენს ანგარიშში",
  "login.email": "ელ-ფოსტა",
  "login.password": "პაროლი",
  "login.button": "შესვლა",
  "login.forgotPassword": "დაგავიწყდათ პაროლი?",
  "login.noAccount": "არ გაქვთ ანგარიში?",
  "login.signUp": "რეგისტრაცია",
  "contact.title": "დაგვიკავშირდით",
  "contact.subtitle": "დაგვიკავშირდით ნებისმიერი კითხვის ან მხარდაჭერისთვის",
  "contact.sendMessage": "გამოგვიგზავნეთ შეტყობინება",
  "contact.formDesc": "შეავსეთ ქვემოთ მოცემული ფორმა და ჩვენ დაგიკავშირდებით რაც შეიძლება მალე",
  "contact.name": "სახელი",
  "contact.namePlaceholder": "თქვენი სრული სახელი",
  "contact.email": "ელ-ფოსტა",
  "contact.emailPlaceholder": "თქვენი ელ-ფოსტის მისამართი",
  "contact.subject": "თემა",
  "contact.subjectPlaceholder": "რას ეხება?",
  "contact.message": "შეტყობინება",
  "contact.messagePlaceholder": "მოგვიყევით მეტი დეტალები...",
  "contact.sendButton": "შეტყობინების გაგზავნა",
  "contact.getInTouch": "დაგვიკავშირდით",
  "contact.channels": "დაგვიკავშირდით ნებისმიერი ამ არხით",
  "contact.emailLabel": "ელ-ფოსტა",
  "contact.phoneLabel": "ტელეფონი",
  "contact.addressLabel": "მისამართი",
  "contact.businessHours": "სამუშაო საათები",
  "contact.monFri": "ორშაბათი - პარასკევი",
  "contact.monFriHours": "9:00 - 18:00",
  "contact.saturday": "შაბათი",
  "contact.saturdayHours": "10:00 - 16:00",
  "contact.sunday": "კვირა",
  "contact.sundayHours": "დაკეტილია",
  "about.title": "ATV Trader-ის შესახებ",
  "about.subtitle": "ჩვენ ვართ წამყვანი მარკეტპლეისი ყველა ტიპის კვადროციკლებისთვის.",
  "about.ourStory": "ჩვენი ისტორია",
  "about.storyP1": "2010 წელს დაარსებული კვადროციკლის მოყვარულთა ჯგუფის მიერ, ATV Trader შეიქმნა.",
  "about.storyP2": "რაც მცირე საზოგადოების ფორუმად დაიწყო, გადაიქცა ჩრდილოეთ ამერიკის უდიდეს კვადროციკლების მარკეტპლეისად.",
  "about.storyP3": "დღეს ჩვენ ამაყად ვემსახურებით როგორც რეკრეაციულ მხედრებს, ასევე პროფესიონალ დილერებს.",
  "about.ourMission": "ჩვენი მისია",
  "about.missionP1": "შევქმნათ ყველაზე სანდო მარკეტპლეისი კვადროციკლების მოყვარულთათვის.",
  "about.missionP2": "ჩვენ გვჯერა, რომ თავგადასავალი ყველასთვის ხელმისაწვდომი უნდა იყოს.",
  "about.whyChoose": "რატომ აირჩიოთ ATV Trader?",
  "about.communityFirst": "საზოგადოება პირველ ადგილზე",
  "about.communityFirstDesc": "შექმნილი კვადროციკლის მოყვარულთა მიერ, კვადროციკლის მოყვარულთათვის.",
  "about.trustedMarketplace": "სანდო მარკეტპლეისი",
  "about.trustedMarketplaceDesc": "დადასტურებული დილერები და კერძო გამყიდველები.",
  "about.qualityGuaranteed": "ხარისხი გარანტირებული",
  "about.qualityGuaranteedDesc": "ყველა განცხადება შემოწმებულია.",
  "about.nationwideReach": "ქვეყნის მასშტაბით",
  "about.nationwideReachDesc": "იპოვეთ კვადროციკლები ქვეყნის ნებისმიერ წერტილში.",
  "about.byTheNumbers": "რიცხვებით",
  "about.activeListings": "აქტიური განცხადებები",
  "about.registeredUsers": "რეგისტრირებული მომხმარებლები",
  "about.verifiedDealers": "დადასტურებული დილერები",
  "about.yearsExperience": "წლიანი გამოცდილება",
  "about.meetTeam": "გაიცანით ჩვენი გუნდი",
  "about.teamDesc": "ჩვენ ვართ კვადროციკლის მოყვარულთა, დეველოპერებისა და მომხმარებელთა მომსახურების ექსპერტთა გუნდი.",
  "about.ceo": "აღმასრულებელი დირექტორი",
  "about.ceoDesc": "30+ წლიანი კვადროციკლის გამოცდილება",
  "about.headProduct": "პროდუქტის ხელმძღვანელი",
  "about.headProductDesc": "ტექნოლოგიური ლიდერი რასინგის გამოცდილებით",
  "about.customerSuccess": "მომხმარებელთა წარმატება",
  "about.customerSuccessDesc": "ეძღვნება მომხმარებელთა კმაყოფილებას",
  "dealers.title": "კვადროების დილერები",
  "dealers.findNearYou": "იპოვეთ კვადროების დილერები თქვენთან ახლოს",
  "dealers.description": "დილერების კატალოგი აქ განთავსდება.",
  "blog.title": "ბლოგი",
  "blog.heading": "კვადროციკლების სიახლეები, რჩევები და გზამკვლევები",
  "blog.description": "ბლოგის სტატიები, სიახლეები და კონტენტი აქ განთავსდება.",
  "research.title": "კვლევა",
  "research.heading": "კვადროციკლების კვლევა და მიმოხილვები",
  "research.description": "კვადროციკლების სპეციფიკაციები, მიმოხილვები და კვლევის ინსტრუმენტები აქ განთავსდება.",
  "notFound.title": "404",
  "notFound.message": "უპს! გვერდი ვერ მოიძებნა",
  "notFound.returnHome": "მთავარ გვერდზე დაბრუნება",
  "recommended.title": "რეკომენდებული კვადროციკლები",
  "recommended.viewAll": "ყველა რეკომენდაციის ნახვა",
  "recommended.save": "დაზოგეთ",
  "terms.title": "მომსახურების პირობები",
  "privacy.title": "კონფიდენციალურობის პოლიტიკა",
};
